### ISSUE TITLE
Incorrect death message

### ISSUE THREAD

**Issue by ImpulsiveLad** [EliteMasterEric/Coroner#14]
I didn't ss it but when killed by a mauler I got "Got mauled to death by a Coil-Head"

**Comment by EliteMasterEric** [comment]
Are you sure everyone has the correct version of Coroner? What other mods do you have installed?

**Comment by ImpulsiveLad** [comment]
I have it in the thunderstore launcher so its the most recent version.
I'm playing with my modpack
Its BepInEx, LC_API, Skinwalkers, More Emotes, Late Company, Ship Loot, WalkieUse, FlashlightToggle, Additional Suits, Weather Multipliers, More Company, Masked Enemy Overhaul, Coroner, AlwaysHearActiveWalkies, MoreItems, EmployeeAssignments, LethalCompanyDRP, More Scream, HDLethalCompany, SuitSaver, MoreBlood, HideModList, CoilHeadStare, Permanant Moons, ShipClock, LBtoKG, HealthMetrics, LethalProgression+, HideChat, and HidePlayerNames
