### ISSUE TITLE
Translation and LCAPI's compatibility problem.

### ISSUE THREAD

**Issue by Greygreygod** [EliteMasterEric/Coroner#18]
When I using Coroner version 1.5.0 with LC API 3.0.2,I don't know why I can't be hurt in game.
And i don't know how to make the font loaded when i trying to make a translate about chinese(Notes doesn't show up when i in settle accountsm,so i just presumably that's the problem),Sorry i am not the programmer that i don't know how to deal with it.
i used to use the XUnity.AutoTranslator to help me with the translation,i want to transfer it to version 1.5.0.

**Comment by EliteMasterEric** [comment]
LC_API dependency has been re-disabled and will not be re-enabled.
