### ISSUE TITLE
Soft lock in multiplayer when leaving a planet when using the More Company mod

### ISSUE THREAD

**Issue by fuchsia-spinel** [EliteMasterEric/Coroner#2]
This mod is causing a soft lock in multiplayer when leaving a planet when using the More Company mod. You're just stuck staring at the open door on the back of the ship. Single-player is unaffected.

**Comment by EliteMasterEric** [comment]
This bug previously existed on version 1.0.0 of the mod. The mod has since been rigorously tested with various counts with More Company installed.

Are you sure the mod is updated to the latest version?

**Comment by fuchsia-spinel** [comment]
Did you want me to share my r2modman profile code in case it's an issue with one of the mods I'm using?

**Comment by EliteMasterEric** [comment]
sure

**Comment by EliteMasterEric** [comment]
Should be fixed in 1.3.0
