### ISSUE TITLE
Having trouble translating into Chinese

### ISSUE THREAD

**Issue by RAINighty** [EliteMasterEric/Coroner#23]
```
<DeathOtherItemDropship text="Couldn't wait for their array." />
<DeathOtherItemDropship text="Got too impatient for their array." />
```
How do you understand this? Is it a coroutine programming meme?

**Comment by EliteMasterEric** [comment]
> ```
> <DeathOtherItemDropship text="Couldn't wait for their array." />
> <DeathOtherItemDropship text="Got too impatient for their array." />
> ```
> 
> How do you understand this? Is it a coroutine programming meme?

This is a typo. It should read "Couldn't wait for their items" and "Got too impatient for their items" respectively.

**Comment by RAINighty** [comment]
I see. My colleagues and I thought it was some kind of programming meme. These two paragraphs have been correctly translated in the pr I submitted, and I hope they can be used in the next update.

**Comment by EliteMasterEric** [comment]
You can see in the current source code that the names are fixed, and I also added some translation notes since some people were confused about a few of the references.
