### ISSUE TITLE
[Compatibility] BetterEXP

### ISSUE THREAD

**Issue by YoBii** [EliteMasterEric/Coroner#26]
BetterEXP adds improved versions of default notes on the performance report including stats e.g. `Most profitable (240 credits)`.

It's a nice touch.

I think previously Coroner was overwriting BXP's notes which was fine because they kind of worked together. We got the changes to the XP system and only missed out on the notes. But now it seems like BXP is overwriting Coroners notes which defeats the purpose of Coroner.

Maybe you can figure something out with the dev? Possibly append messages instead of replace?

Having _notes_ from BXP and _causes of death_ for dead players from Coroner could be one possible solution.

**Comment by Swaggies** [comment]
recommend you close this since it's resolved as of [BetterEXP 1.2.0](https://github.com/Swaggies/BetterEXP/releases/tag/v1.2.0) now.
