### ISSUE TITLE
[Suggestion] Death Messages as Configs

### ISSUE THREAD

**Issue by Carrot9943** [EliteMasterEric/Coroner#27]
First of all, no actual issues so far. Definitely been enjoying the mod.

I think it would be fun to be able to customize/add death messages as well as the funny notes in an actual config file. I'm not sure how that would work with the language support though, if at all. It would be neat for hosts to be able to add their own messages based on their party, like "So and so trusted another person's leadership" or "Took a nap. Nobody noticed."

Just the more customization the better, if possible. Plus, less work for you guys adding more default messages.

**Comment by EliteMasterEric** [comment]
This is already possible. Just modify the English localization file. If you want to sync the changes between clients, create a modpack that includes the config.
