### ISSUE TITLE
Should I worry about this in the console or not?

### ISSUE THREAD

**Issue by Paradox75831004** [EliteMasterEric/Coroner#30]
I use the RTLC translator. What is he swearing at? It works stably, but every time I notice this warning and error. Is there anything wrong?

018d8f2d-3732-00a0-1791-14ee8e2d38d5 - My build

![image](https://github.com/EliteMasterEric/Coroner/assets/72872478/e32b6635-f87e-4f2b-a3c2-3d93753dd2c2)

**Comment by Paradox75831004** [comment]
![image](https://github.com/EliteMasterEric/Coroner/assets/72872478/9f8be4d5-de7e-4cdb-abc9-ea1d55885436)

**Comment by DannBoMambo** [comment]
This error started popping up for me as well in the last update and mod has since stopped working

018ddd73-07b3-78f7-3289-b4e22454732b

**Comment by DannBoMambo** [comment]
Manually downloading and placing https://github.com/EliteMasterEric/Coroner/blob/master/LanguageData/Strings_en.xml in ...\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Default\BepInEx\config\EliteMasterEric-Coroner fixes the issue and the mod works again, though I'm not sure why I had to download the file manually to get it to work when it worked previously.

**Comment by EliteMasterEric** [comment]
Does it work fine when you uninstall it and reinstall from scratch?

**Comment by DannBoMambo** [comment]
I did a clean reinstall on a new profile and all the language data reappeared. I have no idea what caused them to disappear tho.

**Comment by EliteMasterEric** [comment]
Oh yeah an update fixed this.
