### ISSUE TITLE
[Bug] 1.6.1 not finding configs correctly

### ISSUE THREAD

**Issue by ajsglist** [EliteMasterEric/Coroner#31]
New update appears to have a problem finding config files that are definitely there.  Installed via mod manager, double checked with manual install (both have same error)

[Info   :   Coroner] Injecting patch into Landmine.SpawnExplosion...
[Info   :   Coroner] Done.
[Info   :   Coroner] Plugin Coroner (com.elitemastereric.coroner) is loaded!
[Info   :   Coroner] Coroner loading Language Support: en
[Info   :   Coroner] Loading Coroner language data from config folder, at D:\r2modman\LethalCompany\profiles\NotSoEvilDead\BepInEx\config/EliteMasterEric-Coroner
[Error  :   Coroner] Config folder not found at: D:\r2modman\LethalCompany\profiles\NotSoEvilDead\BepInEx\config/EliteMasterEric-Coroner
[Error  :   Coroner] Try reinstalling the mod from scratch.
[Info   :   Coroner] Coroner loading Language Support: en
[Info   :   Coroner] Loading Coroner language data from config folder, at D:\r2modman\LethalCompany\profiles\NotSoEvilDead\BepInEx\config/EliteMasterEric-Coroner
[Error  :   Coroner] Config folder not found at: D:\r2modman\LethalCompany\profiles\NotSoEvilDead\BepInEx\config/EliteMasterEric-Coroner
[Error  :   Coroner] Try reinstalling the mod from scratch.
[Info   :   Coroner] Checking for LC_API...
[Info   :   Coroner] LCAPI is not present.
[Info   :   Coroner] LC_API is not present! Skipping registration...

**Comment by BellaRoka** [comment]
Having the same issue with the latest version. This caused Coroner to default to the "serious" death messages for me as well.

**Comment by EliteMasterEric** [comment]
This was fixed in 1.6.2
