### ISSUE TITLE
[BUG] Coroner breaks on version 55/56

### ISSUE THREAD

**Issue by ZapGamer** [EliteMasterEric/Coroner#34]
![immagine](https://github.com/EliteMasterEric/Coroner/assets/73616891/c4c22725-12a5-4aa0-aa92-3236345b0583)

Just wanted to point this out if it's a problem.

**Comment by EliteMasterEric** [comment]
Coroner straight up doesn't support v55 right now.

**Comment by EliteMasterEric** [comment]
Resolved in v2.0.0
