### ISSUE TITLE
No permission to go new pull reequests, I want to update zh-cn.xml to v56.

### ISSUE THREAD

**Issue by NakiriFox** [EliteMasterEric/Coroner#35]
Display this content after submission：Pull request creation failed. Validation failed: must be a collaborator

**Comment by EliteMasterEric** [comment]
I will look into getting this implemented.

Also you should be able to make a PR?

**Comment by NakiriFox** [comment]
Display this content after submission：Pull request creation failed. Validation failed: must be a collaborator

**Comment by EliteMasterEric** [comment]
This got done.

**Comment by NakiriFox** [comment]
I will update zh-cn.xml to v2.1.0 in tommorrow.
