### ISSUE TITLE
LC_API is listed as a dependency even though it's deemed "Optional" in ReadMe text.

### ISSUE THREAD

**Issue by Afrasabi** [EliteMasterEric/Coroner#4]
Please removed LC_API as a dependency for the mod if it's truly optional as this prevents the mod from being used if LC_API is not also installed/enabled.

Lethal Company mods that replace/add sounds or music currently experience issues when LC_API is enabled, as it attempts to load the .wav files as AssetBundles.

**Comment by EliteMasterEric** [comment]
This is currently slated for the work-in-progress 1.2.0 version.

**Comment by EliteMasterEric** [comment]
Was fixed in 1.3.0

**Comment by StarsDown64** [comment]
Rerequesting this, as those who don't want to install LC_API can't use the mod. imo, if you say it's optional, it should be optional.
