### ISSUE TITLE
{Request} Allow us to customize the messages in config

### ISSUE THREAD

**Issue by santocraft** [EliteMasterEric/Coroner#5]
We would like to customize the messages from the game, it would be a nice addition with friends!

**Comment by EliteMasterEric** [comment]
This would require some way of syncing the custom messages between different client configs. I think this is probably out of scope.

**Comment by EliteMasterEric** [comment]
Reopening this because #12 might actually help a lot with making this feasible.

**Comment by EliteMasterEric** [comment]
This will be supported in 1.5.0, you will be able to edit the language strings and see the result.
