### ISSUE TITLE
Bigger Company isn't a mod in README

### ISSUE THREAD

**Issue by Jatc252** [EliteMasterEric/Coroner#56]
I've tried to google in order to put a link to it but I've got no idea what "BiggerCompany" is so I can't reference to it in the readme. Did you mean [Bigger Lobby](https://thunderstore.io/c/lethal-company/p/bizzlemip/BiggerLobby/)?

**Comment by EliteMasterEric** [comment]
It's probably Bigger Lobby I was referring to.

Mod is deprecated anyway so the reference can just be removed

**Comment by Jatc252** [comment]
Fixed in #54
