### ISSUE TITLE
Buggy bracken, fps drop and teleportation

### ISSUE THREAD

**Issue by ChangeOtaku** [EliteMasterEric/Coroner#7]
Today, me and my friends had some sudden problems:
1- When the Bracken caught someone, he and the player would just get stuck forever in the kill animation
2- One of us had some weird fps drops happening every few minutes
3- One of us sometimes teleported to the floor below/above him
4- When spectating, the player would be walking inside of walls (just from the spec perspective)

I spent some hours removing all the mods i added today and adding them back one by one, it ended up being this mod's fault.

**Comment by EliteMasterEric** [comment]
The players-not-dying issue is definitely #8 which has already been reported and a fix in development.

Once the update is complete, I will close this unless you can definitively tie points 2, 3, and 4 to this mod (when you launch with mods, you should see a log you can copy from).

**Comment by ChangeOtaku** [comment]
thanks for the answer, and for already working on this issue, i would just recommend 2 things:
1- in the mod's page, add "known issues" (if there are other known issues, of course), this would've helped save me some time
2- the discord link you used is direct to a channel, i thin it would be better to also give the server's invite, since i couldnt find the server you mentioned

**Comment by EliteMasterEric** [comment]
Should be fixed with v1.3.1. Let me know.
