### ISSUE TITLE
Log messages

### ISSUE THREAD

**Issue by KlutzyBubbles** [EliteMasterEric/Coroner#9]
Wondering if some of the log messages can be knocked down from Info to debug. And some of the warning messages removed.

Some examples:

`Plugin.Instance.PluginLogger.LogInfo("Handling Thumper damage...");` 
`Plugin.Instance.PluginLogger.LogInfo("Player is now dead! Setting special cause of death...");`
 Seems like something that could be debug

`Plugin.Instance.PluginLogger.LogWarning("Player is somehow still alive! Skipping...");` This might be a warning for one shot enemies, but is just spammed in logs on enemies like thumpers, loot bugs, spiders etc.

This would definitely help reduce log spam without actually losing any information for debugging.

**Comment by EliteMasterEric** [comment]
Version 1.4.0 changes a bunch of log messages to Debug.
